### ISSUE TITLE
Make `withdraw_anchor_account` optional in `WithdrawTransaction` interface

### ISSUE THREAD

**Issue by piyalbasu** [stellar/typescript-wallet-sdk#157]
More context here:

https://stellarfoundation.slack.com/archives/C04ECVCV162/p1721926361224189

**Comment by CassioMG** [comment]
@piyalbasu FYI I'm renaming this task as it appears the goal here is to simply make the `withdraw_anchor_account` field `optional` on the `transaction object` instead of making it optional on the `transferWithdrawalTransaction` function.

The `withdraw_anchor_account` should only be required once the transaction achieves the `pending_user_transfer_start` status, so that it should `throw an error` in case it is still missing once on the `pending_user_transfer_start` status.

This is what this PR is telling me: https://github.com/stellar/kotlin-wallet-sdk/pull/136/files

**Comment by CassioMG** [comment]
Opened PR for the TS Wallet SDK here: https://github.com/stellar/typescript-wallet-sdk/pull/164

**Comment by CassioMG** [comment]
Above PR is merged.
